In [4]:
import pandas as pd
import os

In [5]:
data_folder = '../data/'
all_dataframes = []

#create the good colum names
column_names = [
    'Link no', 'Name',
    'Start_LRP', 'Start_Offset', 'Start_Chainage',
    'End_LRP', 'End_Offset', 'End_Chainage',
    'Length_Km', 'Heavy_Truck', 'Medium_Truck', 'Small_Truck',
    'Large_Bus', 'Medium_Bus', 'Micro_Bus', 'Utility',
    'Car', 'Auto_Rickshaw', 'Motor_Cycle', 'Bi_Cycle',
    'Cycle_Rickshaw', 'Cart', 'Motorized', 'Non_Motorized', 'Total_AADT'
]

for filename in os.listdir(data_folder):
    if filename.endswith(".traffic.htm"):
        file_path = os.path.join(data_folder, filename)
        tables = pd.read_html(file_path, encoding='ISO-8859-1')
        if len(tables) > 0:
            #get the last table, and we only need the first 25 columns.
            df = tables[-1].iloc[:, :25]

            #skip the first three lines with html, and get the real data
            df = df.iloc[3:].copy()

            #make it the right column names
            df.columns = column_names

            #add the road
            df['Road'] = filename.split('.')[0]

            all_dataframes.append(df)

#put all together
final_df = pd.concat(all_dataframes, ignore_index=True)

#road is final column
cols = ['Road'] + [c for c in final_df.columns if c != 'Road']
final_df = final_df[cols]

# Toon het resultaat
display(final_df.head())

,Road,Link no,Name,Start_LRP,Start_Offset,Start_Chainage,End_LRP,End_Offset,End_Chainage,Length_Km,...,Utility,Car,Auto_Rickshaw,Motor_Cycle,Bi_Cycle,Cycle_Rickshaw,Cart,Motorized,Non_Motorized,Total_AADT
0,N1,N1-1L,Jatrabari - Int.with Z1101 (Left) (Left),LRPS,0,0,LRPS,822,0.822,0.822,...,238.0,1851.0,2980.0,398.0,232.0,889.0,0.0,18236.0,1121.0,19357.0
1,N1,N1-1R,Jatrabari - Int.with Z1101 (Left) (Right),LRPS,0,0,LRPS,822,0.822,0.822,...,480.0,2608.0,2508.0,436.0,213.0,1088.0,0.0,20236.0,1301.0,21537.0
2,N1,N1-2L,Int.with Z1101 - Signboard (Left) R111 (Left),LRPS,822,0.822,LRPS,4175,4.175,3.353,...,480.0,2608.0,2508.0,436.0,213.0,1088.0,0.0,20236.0,1301.0,21537.0
3,N1,N1-2R,Int.with Z1101 - Signboard (Left) R111 (Right),LRPS,822,0.822,LRPS,4175,4.175,3.353,...,238.0,1851.0,2980.0,398.0,232.0,889.0,0.0,18236.0,1121.0,19357.0
4,N1,N1-3L,Signboard - Shimrail (Left)R110 (Left),LRPS,4175,4.175,LRPS,7181,7.181,3.006,...,314.0,1690.0,2266.0,1087.0,75.0,1198.0,0.0,16288.0,1273.0,17561.0

In [6]:
display(final_df.tail())

,Road,Link no,Name,Start_LRP,Start_Offset,Start_Chainage,End_LRP,End_Offset,End_Chainage,Length_Km,...,Utility,Car,Auto_Rickshaw,Motor_Cycle,Bi_Cycle,Cycle_Rickshaw,Cart,Motorized,Non_Motorized,Total_AADT
177,N208,N208-1,Moulvibazar-Int.with Z2002,LRPS,0,0,LRPS,3190,3.19,3.190,...,149.0,741.0,3194.0,1123.0,147.0,486.0,0.0,7514.0,633.0,8147.0
178,N208,N208-2,Int.with Z2002-Rajnagar (Int.with R281),LRPS,3190,3.19,LRP012,1661,13.461,10.271,...,149.0,741.0,3194.0,1123.0,147.0,486.0,0.0,7514.0,633.0,8147.0
179,N208,N208-3,Rajnagar(Int.with R281)-Daudabad (Int.with Z2832),LRP012,1661,13.461,LRP052,385,51.05,37.589,...,78.0,811.0,2233.0,582.0,88.0,73.0,0.0,5328.0,161.0,5489.0
180,N208,N208-4,Daudabad (Int.with Z2832)-Royal City Chottor(i...,LRP052,385,51.05,LRP054,677,53.342,2.292,...,78.0,811.0,2233.0,582.0,88.0,73.0,0.0,5328.0,161.0,5489.0
181,N208,N208-5,Royal City Chottor(int.with N210)-Int.with N2,LRP054,677,53.342,LRP058,900,57.495,4.153,...,77.0,778.0,2974.0,1231.0,695.0,822.0,47.0,9488.0,1564.0,11052.0

In [7]:
#check for example the N106
n106_data = final_df[final_df['Road'] == 'N106']
display(n106_data)

,Road,Link no,Name,Start_LRP,Start_Offset,Start_Chainage,End_LRP,End_Offset,End_Chainage,Length_Km,...,Utility,Car,Auto_Rickshaw,Motor_Cycle,Bi_Cycle,Cycle_Rickshaw,Cart,Motorized,Non_Motorized,Total_AADT
133,N106,N106-1,Chittagong (Oxygen More)-Hathazari (Int. with ...,LRPS,0,0,LRP010,2084,12.192,12.192,...,289.0,1063.0,8817.0,1355.0,234.0,393.0,0.0,17165.0,627.0,17792.0
134,N106,N106-2,Hathazari (Int. with R160)-Gohira(Int.with Z1619),LRP010,2084,12.192,LRP018,1533,19.321,7.129,...,217.0,296.0,5481.0,1078.0,576.0,943.0,0.0,8908.0,1519.0,10427.0
135,N106,N106-3,Gohira(Int.with Z1619)-Munshihat (Int.with Z1629),LRP018,1533,19.321,LRP024,828,24.297,4.976,...,217.0,296.0,5481.0,1078.0,576.0,943.0,0.0,8908.0,1519.0,10427.0
136,N106,N106-4,Munshihat (Int.with Z1629)-Raozan (Int.with Z1...,LRP024,828,24.297,LRP025,820,25.278,0.981,...,217.0,296.0,5481.0,1078.0,576.0,943.0,0.0,8908.0,1519.0,10427.0
137,N106,N106-5,Raozan (Int.with Z1012)-Ranirhat (Int.with Z1613),LRP025,820,25.278,LRP039,690,37.25,11.972,...,418.0,103.0,520.0,372.0,0.0,0.0,0.0,2443.0,0.0,2443.0
138,N106,N106-6,Ranirhat (Int.with Z1613)-Gabtoli (Int.with Z1...,LRP039,690,37.25,LRP044,296,41.825,4.575,...,418.0,103.0,520.0,372.0,0.0,0.0,0.0,2443.0,0.0,2443.0
139,N106,N106-7,Gabtoli (Int.with Z1617)-Ghagra (Int. with R161),LRP044,296,41.825,LRP051,147,48.879,7.054,...,418.0,103.0,520.0,372.0,0.0,0.0,0.0,2443.0,0.0,2443.0
140,N106,N106-8,Ghagra (Int. with R161)-Manikchhari(Int. with ...,LRP051,147,48.879,LRP059,566,57.303,8.424,...,83.0,35.0,904.0,471.0,0.0,0.0,0.0,1975.0,0.0,1975.0
141,N106,N106-9,Manikchhari(Int. with R162)-Rangamati,LRP059,566,57.303,LRPE,0,66.85,9.547,...,83.0,35.0,904.0,471.0,0.0,0.0,0.0,1975.0,0.0,1975.0

In [19]:
final_df_index = final_df.copy()
final_df_index['End_Chainage'] = final_df_index['End_Chainage'].astype(float).astype(str)
final_df_index['Index'] = final_df_index['Road'] + '-' + final_df_index['End_Chainage']
final_df_index

,Road,Link no,Name,Start_LRP,Start_Offset,Start_Chainage,End_LRP,End_Offset,End_Chainage,Length_Km,...,Car,Auto_Rickshaw,Motor_Cycle,Bi_Cycle,Cycle_Rickshaw,Cart,Motorized,Non_Motorized,Total_AADT,Index
0,N1,N1-1L,Jatrabari - Int.with Z1101 (Left) (Left),LRPS,0,0,LRPS,822,0.822,0.822,...,1851.0,2980.0,398.0,232.0,889.0,0.0,18236.0,1121.0,19357.0,N1-0.822
1,N1,N1-1R,Jatrabari - Int.with Z1101 (Left) (Right),LRPS,0,0,LRPS,822,0.822,0.822,...,2608.0,2508.0,436.0,213.0,1088.0,0.0,20236.0,1301.0,21537.0,N1-0.822
2,N1,N1-2L,Int.with Z1101 - Signboard (Left) R111 (Left),LRPS,822,0.822,LRPS,4175,4.175,3.353,...,2608.0,2508.0,436.0,213.0,1088.0,0.0,20236.0,1301.0,21537.0,N1-4.175
3,N1,N1-2R,Int.with Z1101 - Signboard (Left) R111 (Right),LRPS,822,0.822,LRPS,4175,4.175,3.353,...,1851.0,2980.0,398.0,232.0,889.0,0.0,18236.0,1121.0,19357.0,N1-4.175
4,N1,N1-3L,Signboard - Shimrail (Left)R110 (Left),LRPS,4175,4.175,LRPS,7181,7.181,3.006,...,1690.0,2266.0,1087.0,75.0,1198.0,0.0,16288.0,1273.0,17561.0,N1-7.181
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
177,N208,N208-1,Moulvibazar-Int.with Z2002,LRPS,0,0,LRPS,3190,3.19,3.190,...,741.0,3194.0,1123.0,147.0,486.0,0.0,7514.0,633.0,8147.0,N208-3.19
178,N208,N208-2,Int.with Z2002-Rajnagar (Int.with R281),LRPS,3190,3.19,LRP012,1661,13.461,10.271,...,741.0,3194.0,1123.0,147.0,486.0,0.0,7514.0,633.0,8147.0,N208-13.461
179,N208,N208-3,Rajnagar(Int.with R281)-Daudabad (Int.with Z2832),LRP012,1661,13.461,LRP052,385,51.05,37.589,...,811.0,2233.0,582.0,88.0,73.0,0.0,5328.0,161.0,5489.0,N208-51.05
180,N208,N208-4,Daudabad (Int.with Z2832)-Royal City Chottor(i...,LRP052,385,51.05,LRP054,677,53.342,2.292,...,811.0,2233.0,582.0,88.0,73.0,0.0,5328.0,161.0,5489.0,N208-53.342
181,N208,N208-5,Royal City Chottor(int.with N210)-Int.with N2,LRP054,677,53.342,LRP058,900,57.495,4.153,...,778.0,2974.0,1231.0,695.0,822.0,47.0,9488.0,1564.0,11052.0,N208-57.495

In [8]:
roads_csv = pd.read_csv('../data/_roads3.csv')
roads_csv

,road,chainage,lrp,lat,lon,gap,type,name
0,N1,0.000,LRPS,23.706028,90.443333,NaN,Others,Start of Road after Jatrabari Flyover infront...
1,N1,0.814,LRPSa,23.702917,90.450417,NaN,Culvert,Box Culvert
2,N1,0.822,LRPSb,23.702778,90.450472,NaN,CrossRoad,Intersection with Z1101
3,N1,1.000,LRP001,23.702139,90.451972,NaN,KmPost,Km post missing
4,N1,2.000,LRP002,23.697889,90.460583,NaN,KmPost,Km post missing
...,...,...,...,...,...,...,...,...
51343,Z8943,7.000,LRP007,22.429499,90.785722,NaN,KmPost,Km Post Missing
51344,Z8943,8.000,LRP008,22.430110,90.776333,NaN,KmPost,Km Post Missing
51345,Z8943,8.133,LRP008a,22.430249,90.774888,BS,Bridge,Start of Bridge
51346,Z8943,8.151,LRP008b,22.430249,90.774860,BE,Bridge,End of Bridge
51347,Z8943,8.800,LRPE,22.430166,90.768916,NaN,Others,"End at Kunjerhat Bazar and intersct with R890,..."

In [16]:
roads_csv_index = roads_csv.copy()
roads_csv_index['Index'] = roads_csv_index['road'] + "-" + roads_csv_index['chainage'].astype(str)
roads_csv_index

,road,chainage,lrp,lat,lon,gap,type,name,Index
0,N1,0.000,LRPS,23.706028,90.443333,NaN,Others,Start of Road after Jatrabari Flyover infront...,N1-0.0
1,N1,0.814,LRPSa,23.702917,90.450417,NaN,Culvert,Box Culvert,N1-0.814
2,N1,0.822,LRPSb,23.702778,90.450472,NaN,CrossRoad,Intersection with Z1101,N1-0.822
3,N1,1.000,LRP001,23.702139,90.451972,NaN,KmPost,Km post missing,N1-1.0
4,N1,2.000,LRP002,23.697889,90.460583,NaN,KmPost,Km post missing,N1-2.0
...,...,...,...,...,...,...,...,...,...
51343,Z8943,7.000,LRP007,22.429499,90.785722,NaN,KmPost,Km Post Missing,Z8943-7.0
51344,Z8943,8.000,LRP008,22.430110,90.776333,NaN,KmPost,Km Post Missing,Z8943-8.0
51345,Z8943,8.133,LRP008a,22.430249,90.774888,BS,Bridge,Start of Bridge,Z8943-8.133
51346,Z8943,8.151,LRP008b,22.430249,90.774860,BE,Bridge,End of Bridge,Z8943-8.151
51347,Z8943,8.800,LRPE,22.430166,90.768916,NaN,Others,"End at Kunjerhat Bazar and intersct with R890,...",Z8943-8.8

In [20]:
lets_see = pd.merge(final_df_index, roads_csv_index, how='left', on='Index')
lets_see

,Road,Link no,Name,Start_LRP,Start_Offset,Start_Chainage,End_LRP,End_Offset,End_Chainage,Length_Km,...,Total_AADT,Index,road,chainage,lrp,lat,lon,gap,type,name
0,N1,N1-1L,Jatrabari - Int.with Z1101 (Left) (Left),LRPS,0,0,LRPS,822,0.822,0.822,...,19357.0,N1-0.822,N1,0.822,LRPSb,23.702778,90.450472,NaN,CrossRoad,Intersection with Z1101
1,N1,N1-1R,Jatrabari - Int.with Z1101 (Left) (Right),LRPS,0,0,LRPS,822,0.822,0.822,...,21537.0,N1-0.822,N1,0.822,LRPSb,23.702778,90.450472,NaN,CrossRoad,Intersection with Z1101
2,N1,N1-2L,Int.with Z1101 - Signboard (Left) R111 (Left),LRPS,822,0.822,LRPS,4175,4.175,3.353,...,21537.0,N1-4.175,N1,4.175,LRP004a,23.693805,90.480527,NaN,"SideRoad,Right",Road to Narayanganj(R111)
3,N1,N1-2R,Int.with Z1101 - Signboard (Left) R111 (Right),LRPS,822,0.822,LRPS,4175,4.175,3.353,...,19357.0,N1-4.175,N1,4.175,LRP004a,23.693805,90.480527,NaN,"SideRoad,Right",Road to Narayanganj(R111)
4,N1,N1-3L,Signboard - Shimrail (Left)R110 (Left),LRPS,4175,4.175,LRPS,7181,7.181,3.006,...,17561.0,N1-7.181,N1,7.181,LRP007a,23.697916,90.509278,NaN,CrossRoad,"R110,Left to Demra, Right to Narayanganj"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
177,N208,N208-1,Moulvibazar-Int.with Z2002,LRPS,0,0,LRPS,3190,3.19,3.190,...,8147.0,N208-3.19,N208,3.190,LRP003a,24.490972,91.774499,NaN,"SideRoad,Right","Z2002,Moulavibazar-Chatla Cheek post road"
178,N208,N208-2,Int.with Z2002-Rajnagar (Int.with R281),LRPS,3190,3.19,LRP012,1661,13.461,10.271,...,8147.0,N208-13.461,N208,13.461,LRP013b,24.517944,91.859972,NaN,"SideRoad,Right","R281,Rajnagar-Charkhai road"
179,N208,N208-3,Rajnagar(Int.with R281)-Daudabad (Int.with Z2832),LRP012,1661,13.461,LRP052,385,51.05,37.589,...,5489.0,N208-51.05,N208,51.050,LRP052b,24.828694,91.900056,NaN,"SideRoad,Right","Z2832,Daudabad-Vdeshwar road"
180,N208,N208-4,Daudabad (Int.with Z2832)-Royal City Chottor(i...,LRP052,385,51.05,LRP054,677,53.342,2.292,...,5489.0,N208-53.342,N208,53.342,LRP054a,24.848000,91.896583,NaN,"SideRoad,Right","N210, Sylhet Bypass road"
181,N208,N208-5,Royal City Chottor(int.with N210)-Int.with N2,LRP054,677,53.342,LRP058,900,57.495,4.153,...,11052.0,N208-57.495,N208,57.495,LRPE,24.877555,91.875360,NaN,Others,"Road end at Humayun Rashid Chattar, Intersecti..."

In [21]:
lets_see.to_csv('../data/lets_see_eind.csv', index=False)